### ISSUE TITLE
Add weather??

### ISSUE THREAD

**Issue by PengiCoder** [PengiOS/pengios.github.io#1]
open-meteo works at school
https://[api.open-meteo.com/v1/forecast?latitude=-33.8343&longitude=151.1459&hourly=temperature_2m&timeformat=unixtime&timezone=Australia%2FSydney]

**Comment by MrPiggy105** [comment]
on it

we will use https://api.open-meteo.com/v1/forecast?latitude=-33.8678&longitude=151.2073&current=temperature_2m,apparent_temperature,is_day&daily=temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,precipitation_probability_max&timezone=auto&forecast_days=3

**Comment by MrPiggy105** [comment]
Done! More improvements to come
